#!/usr/bin/env ruby

bin_dir = File.expand_path('../bin/', File.dirname(__FILE__))
shell_script_path = File.join(bin_dir, 'git_checkout_target_branches.sh')

exec("#{shell_script_path} #{ARGV.join(' ')}")
